version: '3.8'

services:

  backend:
    image: bloglist-backend-prod
    build:
      context: ./bloglist-app
      dockerfile: Dockerfile
    container_name: bloglist-backend-prod

  frontend:
    image: bloglist-frontend-prod
    build:
      context: ./bloglist-frontend
      dockerfile: Dockerfile
    environment:
      - PORT=80
    container_name: bloglist-frontend-prod

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
       - frontend
       - backend