version: '3.8'

services:

  backend:
    image: bloglist-backend-dev
    build:
      context: ./bloglist-app
      dockerfile: dev.Dockerfile
    volumes:
      - ./bloglist-app:/usr/src/app
    ports:
      - 3003:3003
    container_name: bloglist-backend-dev

  frontend:
    image: bloglist-frontend-dev
    build:
      context: ./bloglist-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./bloglist-frontend:/usr/src/app
    ports:
      - 3000:80
    environment:
      - PORT=80
    container_name: bloglist-frontend-dev

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
       - frontend
       - backend

  debug-helper:
    image: busybox